### ISSUE TITLE
Cache Initial Conditions [Feature Request]

### ISSUE THREAD

**Issue by deckar01** [vivekn/redis-simple-cache#38]
I am planning to implement initial conditions ([seed values](http://en.wikipedia.org/wiki/Initial_condition)). Providing seed values can simplify the body of a recursive function significantly.

I image it looking something like this:

``` python
# Fibonacci
@cache_it(seed={0:0, 1:1})
def F(i): return F(i-1) + F(i-2)
```

Since the seed changes all the values of the function, the seed should be fed into the hash used for the function key.

Are there any other considerations I should take into account before implementation?
Does this sound like it falls within the scope of the goals of this repo?

**Comment by vivekn** [comment]
I am not sure I understand the use case for this. A recursive function which would make a network roundtrip and hit a database at each stack frame, would be slow. If you want to cache the results of such a function it would be better to write a wrapper function and cache the results of that function instead. Can you provide any examples where this might be useful.

**Comment by deckar01** [comment]
My use case is a function that performs a very intensive calculation with
small input and output sizes. More specifically it uses a recurrence
relation to generate an intermediate set that exhibits factorial growth
with respect to the input parameters, then filters over the set to select
elements with a given property which produces a very small output set.

**Comment by szaydel** [comment]
Just giving this a quick thought, I am not sure this is a general enough thing to really be implemented directly in this library. It sounds to me like something you implement as part of the mechanism which uses this library as its building block.

**Comment by deckar01** [comment]
One thing to consider is that this is a generic utility that is useful for any recurrence relation. 2 of the examples in the readme are the Fibonacci sequence which is much more readable when you can define its initial conditions outside of the function body.

Alternatives:

`@recursive_cache(seed={0:0, 1,1})`

This allows `cache_it`'s key generation to be extended and could be included from a separate lib.

```
@seed_it({0:0, 1:1})
@cache_it
```

This is nice too if I can still override `cache_it`'s key generation.

**Comment by deckar01** [comment]
Thanks for your input @vivekn and @szaydel.

Punting this feature until I run into it again.

**Comment by szaydel** [comment]
Never a bad idea to fork and experiment. Cheers!
